import time
from datetime import datetime

print('🔍 MONITORAMENTO ESTRATÉGIAS INDEPENDENTES')
print('=' * 50)
print(f'⏰ Iniciado em: {datetime.now().strftime("%H:%M:%S")}')
print('📊 Aguardando próximo ciclo do bot...')
print('🎯 Expectativa: Sinais de ALAVANCAGEM com EVs ≥ 0.5')
print('💡 Critérios relaxados: MS ≥ 40%, W1S ≥ 50%')
print('')
print('📋 O que observar nos logs:')
print('   ✅ "ESTRATÉGIA: ALAVANCAGEM (EV alto)"')
print('   ✅ EVs altos sendo aceitos (≥ 0.5)')
print('   ✅ Critérios relaxados funcionando')
print('   ✅ Sinais de alavancagem sendo enviados')
print('')
print('⚠️  Se não aparecer em 10 minutos, pode precisar ajuste adicional')
print('')
print('🔄 As estratégias agora operam INDEPENDENTEMENTE:')
print('   🚀 ALAVANCAGEM: EV ≥ 0.5, MS ≥ 40% (relaxado)')
print('   🧠 VANTAGEM MENTAL: EV 0.15-0.49, MS ≥ 60%')
print('   🎯 INVERTIDA: 3º sets, MS ≥ 45%')
print('   📊 RIGOROSA: EV < 0.15, MS ≥ 65%')
print('')
print('✅ DEPLOY REALIZADO - Aguardando resultados...')
